### ISSUE TITLE
サイトについての改善提案

### ISSUE THREAD

**Issue by kazuemon** [JupiterDevelopmentTeam/Jupiter#10]
いくつか思った点を書かさせていただきます。

# 1.対応バージョンの書き換え
「JupiterはJava8で開発され、MinecraftPE_**v1.0.6**に対応しています。」
https://jupiterdevelopmentteam.github.io/#support

# 2.サイトを言語別に分割
README.mdには「日本語に特化」と書かれていますが、サイトのトップページを英語で書くのはどうかと思います。
日本語とEnglishに分けるのはどうでしょうか。

該当部分
>Server software for Minecraft Pocket edition. Most of sources are from Nukkit.
>for under the GNU General Public License v3.0 license.

**Comment by popkechupki** [comment]
意見ありがとうございます。いただいた意見をもとにサイトを改善していきます。
