### ISSUE TITLE
今後について

### ISSUE THREAD

**Issue by itsu020402** [JupiterDevelopmentTeam/Jupiter#11]
今後追加/修正していくことについて
- [x] 実績関係のバグ修正
- [ ] JavaScriptプラグインのサポート
- [ ] バグ修正
- [x] タスクアイコンの機能の追加
- [x] 軽量化

**Comment by fuyutsuki** [comment]
TODOは以下のように書くといいと思います
- [ ] やること1
- [x] やること2

**Comment by itsu020402** [comment]
ありがとうございます。
