### ISSUE TITLE
1.1.0branchのバグについて

### ISSUE THREAD

**Issue by plankton12345** [JupiterDevelopmentTeam/Jupiter#14]
現在確認できているバグ
・シフト状態と通常状態が高速で入れ替わる
・ツール類を使ってブロックを壊そうとすると左に一個ずつ移動し最終的に一番左に行く
・苗や花等を植えれない(火打ち石と打ち金等も同様)
・ブロックも置けない
・弓も撃てない、食糧も食べれない、とにかくPC版での右クリック類が全てダメ
・陸上でも酸素メーターが出る
・ブロックを壊せない
こんな感じでしょうか

**Comment by itsu020402** [comment]
修正済みのバグ
・シフト状態と通常状態が高速で入れ替わる
・ブロックも置けない
・陸上でも酸素メーターが出る
・ブロックを壊せない

**Comment by popkechupki** [comment]
## 残っているバグ
- ツール類を使ってブロックを壊そうとすると左に一個ずつ移動し最終的に一番左に行く
- 苗や花等を植えれない(火打ち石と打ち金等も同様)
- 弓も撃てない、食糧も食べれない、とにかくPC版での右クリック類が全てダメ
- 陸上でも酸素メーターが出る

**Comment by Megapix96** [comment]
右クリ類ですが、釣竿はそもそも釣るボタンが出現しない模様...ClientSideじゃ無くなったってことは意図的にボタンを出現される事が出来るように...!? はならないか

**Comment by Megapix96** [comment]
お肉は食べられますし弓も打てるようになったみたいです
釣り竿はやっぱボタンが表示されないですね
火打石も使えます
陸上のメーター問題は治ってました

**Comment by Megapix96** [comment]
自分の環境だけかもしれないんですが、ダメージを食らったときハートが動いたり効果音がなったりせずにスッと何か機械的にハートが操作されるような描写になるんですが...これは..

**Comment by Megapix96** [comment]
本当に分かりづらく申し訳ないんですが、
GenisysProやPocketMineで先ほど試したダメージだと
バチッっと音がなってハートが赤白黒？と点滅して減るんですね
ですがJupiterはsetHealthで変えたように何も起きずに値だけ減ってる感じがします

**Comment by Megapix96** [comment]
せっかくissue機能があるのに一つのissueのコメント欄に書き込むのもなんなので新しく建てました

**Comment by Megapix96** [comment]
今度からは何かバグを発見した際は新しくissueを立てるようにお願いします。(数がだいぶ減ってきたんで)
その方が修正具合やバグのリストも分かりやすいかなあと
