### ISSUE TITLE
コマンドヘルプが可笑しい

### ISSUE THREAD

**Issue by popkechupki** [JupiterDevelopmentTeam/Jupiter#33]
本来/helpはページ数を指定することで表示内容を変えることができますが、どのページを入力しても1ページ目の内容が表示されてしまいます。

**Comment by Megapix96** [comment]
同時に/help command名も使えなくなっていますね
コンソールでは/help command名は使えました。
commandパラメータ関係なんですかね～。

**Comment by itsu020402** [comment]
1.2で解決しました！
