### ISSUE TITLE
What the fuck you want ? You GET ILLEGAL MY CHANGES.

### ISSUE THREAD

**Issue by NycuRO** [JupiterDevelopmentTeam/Jupiter#42]
Ok, i'm created on Nukkit one PR with Generator where i'm say:

**
" * <p>
 * This generator was written by Creeperface and Nycuro
 * The following classes are theirs and are intended for NUKKIT USAGE and should not be copied/translated to other software
 * such as BukkitPE, ClearSky, Genisys , Pocketmine-MP**

![image](https://user-images.githubusercontent.com/13573011/29176428-887a2cca-7df4-11e7-8d16-8c758226d9d7.png)

Why you copy ?

Lmao.

Delete my changes, now and get yourself. Kiss you.

**Comment by NycuRO** [comment]
![image](https://user-images.githubusercontent.com/13573011/29176497-afb7e520-7df4-11e7-86c4-720b22d97bb6.png)


Delete my changes, now. This is illegal.

**Comment by Megapix96** [comment]
https://github.com/yescallop/Nukkit/pull/47

**Comment by NycuRO** [comment]
@Megapix96 And what?

This is my code and my condition. I don't want steal my code. Please delete them.

**Comment by NycuRO** [comment]
@Megapix96 If @PikyCZ copied your code it's not my fault. Please delete code.

**Comment by itsu020402** [comment]
But why does Nukkit use GPL-License?

**Comment by Megapix96** [comment]
Do you know GNU?

**Comment by popkechupki** [comment]
So... in Japan, now 1.a.m ... we are very sleepy... sorry i will reopen this issue our next morning...

**Comment by NycuRO** [comment]
@popkechupki Can you open now , and stand open, no need.

@itsu020402 You know this is my code no? My code is not for all , sorry. You fucking copy my code and get this illegal.

**Comment by itsu020402** [comment]
@NycuRO
If we delete these codes and rewrite codes from Pocketmine-MP, this is OK?

**Comment by NycuRO** [comment]
@itsu020402 Yes, is ok as long as it is not the nukkit code (My code and Creeper code and code from my existent PR)

**Comment by kazuemon** [comment]
@NycuRO Why do you prohibit copying those codes to other software?

**Comment by kazuemon** [comment]
@NycuRO 
Also why are you prohibiting other software by name?
Do you hate those software?

**Comment by itsu020402** [comment]
@NycuRO
If you prohibit copying Nukkit codes, these are different from GNU Licence. 
If you want to prohibit copying these codes, you should change the license.

**Comment by FireSprout** [comment]
Excuse me from outside contributor (apology).
Why is it not possible to borrow code under GPL license?
I'm sorry to reply suddenly!
Please forgive me! Because I'll do anything you say!
(I don't say to do anything)

**Comment by NycuRO** [comment]
@kazuemon I don't want others shitty unofficials software have a official code and original. I don't want that. Please delete them and change. It's not your decision have this code ;)
Ok @itsu020402 ? Please delete ;)

**Comment by kazuemon** [comment]
@Nycuro Is that to ignore the GPL license?

**Comment by NycuRO** [comment]
@kazuemon I say. I created this for NUKKIT. Not for others. You can use my plugin if you want, ok?

https://github.com/NycuRO/BiomeMaster

**Comment by haniokasai** [comment]
@itsu020402 さっさとブロックしろよ、このハゲー

**Comment by kazuemon** [comment]
@NycuRO 
Again, do you understand the GPL license?
I think that there is a problem with GPL licensing about that rule you wrote ** personal **.
Do we have to keep that rule?

**Comment by kazuemon** [comment]
@NycuRO 
If you think that you must observe this rule, you should change Nukkit 's license first.

**Comment by NycuRO** [comment]
@kazuemon Are you sure about that?

My plugin have one license and them is implemented to Nukkit.
Once implemented, it retains them license.
Now, you can delete.

**Comment by kazuemon** [comment]
@NycuRO 
Does that mean that we should not copy it because your plugin is an Apache license?

**Comment by itsu020402** [comment]
@NycuRO 
I say again:
If you want to prohibit copying Nukkit's codes, please change the license.

**Comment by itsu020402** [comment]
If you won't reply among an hour, this issue will be closed.

**Comment by NycuRO** [comment]
@itsu020402 Ok, you remove code? Yes or no? I don't want steal my time here.

**Comment by itsu020402** [comment]
We cannot do that because arguing that copying Nukkit's codes is illegal under GNU License is illegal.

**Comment by NycuRO** [comment]
@itsu020402 Ok, i report this project.

**Comment by Asuna-Yuuki** [comment]
@NycuRO you shit head just stop first with protocolsuport spaming now this how old are 7
