### ISSUE TITLE
Achivementの需要

### ISSUE THREAD

**Issue by Megapix96** [JupiterDevelopmentTeam/Jupiter#71]
もうMinecraftJEのような実績はありませんし(MinecraftJEですら'進捗'になってしまった)、
BEにあるのはXBoxの実績でサーバー側では管理できない範囲です
サーバーソフト側が作っている実績(パンを作る etc)はもう無いものですので
サーバーに残す必要はあるのでしょうか

**Comment by tedo0627** [comment]
そもそも、あまり使われてなかったのでいいと思います

**Comment by popkechupki** [comment]
確かにありませんね…
強いて言うなら生活鯖で新規ユーザーの様子を見るのに管理的な意味で見てたりするくらいでしょうか…

**Comment by itsu020402** [comment]
使われていないうえにJupiterでの実績のバグが多いので賛成です。
