### ISSUE TITLE
Lights go on and off

### ISSUE THREAD

**Issue by melvincoin** [JupiterDevelopmentTeam/Jupiter#77]
Sorry for typing in English but Japanese is not my native language.
I am running the latest Jupiter build on my Java server. When connecting with a client like my iPad the lights in the world go on and dim all the time.
Black spots appear on objects and go away shortly after they appear. This happens on day and night.
Even with fresh installation, please let me know the solution.
Can upload an movie if needed?

**Comment by itsu020402** [comment]
Thank you for giving us an issue, and you don't have to upload the video.
We've already known such bugs.
But we cannot fix the bug because we cannot find the cause of the bug.

Sorry, and please wait for while fix the bug.

**Comment by melvincoin** [comment]
Thanks, keep on the good work 👌🏻.

**Comment by melvincoin** [comment]
Ps don’t know if you know allready where to search but it has something to do with the shadows.

**Comment by itsu020402** [comment]
We didn't know the cause, so thank you for telling a hint to fix the bug!!
